### PR TITLE
D8CORE-106: Multiple Media Formatter

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR (Initial) REVIEW 

# Summary
- Allows multiple options for an entity reference field referencing media entities.
Screen Shot 2020-01-21 at 4 11 17 PM

# Review By (Date)
- Jan 29th

# Urgency
- Med/Low

# Steps to Test

1. Check out branch https://github.com/SU-SWS/acsf-cardinalsites/pull/51 or review on tugboat build
2. Review code and comment on the approach
3. Log in to the tugboat build and play around with the configuration options `/admin/structure/paragraphs_type/stanford_media_caption/display`

# ToDo
- Revise and add tests.

# Affected Projects or Products
- D8CORE
- Anything using media fields

# Associated Issues and/or People
- D8CORE
- 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
This seems like a decent approach. I'm concerned about how its going to grow with the increase in media types. I'd like to add some `isApplicable` logic so that you could actually eliminate the "Others" area. Make it only for image, video and audio. Maybe even eliminate audio for now.

Also related to your codeclimate issue in the last commit: comment/docblock namespaces must be full name space. all other namespacing should be shortened with `use` statements.

```
/**
 * @param \Drupal\Stuff\Here $var
 */
public function heyThere(Here $var){
}
```

**Comment by sherakama** [comment]
Aye, I hear you about new media types. This is really coupled to the media types in this module so I will look into updating the `isApplicable` logic so that it is wired to just the types in this module.

**Comment by sherakama** [comment]
@pookmish as the multiple media formatter does allow for any media bundle that could be added through the `other` option what additional `isApplicable` restrictions are you looking for?

**Comment by pookmish** [comment]
I was thinking of restricting when the formatter can be applied. because there will eventually be more media types i was hoping to keep the formatter plugin from growing in size. but i guess if all "other" types just inherit the display mode settings my concern might be unjust.

**Comment by pookmish** [comment]
Maybe for now we can remove the audio stuff? we currently don't have any audio media types in the module.

**Comment by sherakama** [comment]
@pookmish Ready for review again.

**Pull request merged**
